### PR TITLE
remove composer.lock

### PR DESCRIPTION
**Pull request by jaymecd**
Vendor lock should not be managed via `composer.lock`, but rather versions in `composer.json`.

### CODE REVIEW

**Comment by ramondelafuente** [comment]
Why would you remove the composer.lock exactly? It is not used when other projects `require` this lib.

**Comment by jaymecd** [comment]
But `require-dev` provides dependencies.

**Comment by jaspernbrouwer** [comment]
Any `composer.lock` that's not _your_ `composer.lock` won't have any effect on the dependencies _you_ install (only `composer.json` does).

The `composer.lock` in this repo is merely there so TravisCI uses the versions I lock them at.

**Comment by jaymecd** [comment]
@jaspernbrouwer I know that, but the problem is in "versions **I lock** them at". 
How often are you going to update it? How fast would you discover bugs due version mismatch (minor/patch) in `other projects` with up-to-date dependencies, which depends on `event-sourcing`?
Eg, check Symfony, Behat and etc... they never commit `composer.lock`

**Comment by ramondelafuente** [comment]
Ok, I see what you mean. Serves me right for not reading Phil's article sooner.

https://philsturgeon.uk/php/2014/11/04/composer-its-almost-always-about-the-lock-file/

Not committing the lockfile would make Travis use the 'latest state of te world' (just like your users are getting, because your lockfile isn't used by them), and would catch problems in dependencies even if you haven't updated locallly.

There would still be a problem though, when a lib stabilizes and has very little activity - so very little travis tests. But that could be fixed with a periodic 'composer update to check depencencies' commit. Doesn't even have to be merged, just a pull request would be enough :-)

Thanks for pointing it out!

This message was sent from my phone and might be a little brief.

**Comment by jaymecd** [comment]
Welcome. Agreed with Phil's article: application should use it, library should not.
Also other `simple-es` repos also should be cleaned up.

**Comment by dennisdegreef** [comment]
I've seen a service pass by which tries to solve this problem. I am trying not to promote commercial products for open source projects (and i'm not affiliated), but it seems free for public projects.
https://www.versioneye.com/ Interesting to say the least :)

https://www.versioneye.com/php/simple-es:event-sourcing/dev-master

**Comment by jaspernbrouwer** [comment]
@jaymecd: I see I misunderstood your point. I have to admit it didn't occur to me that these kind of issues could show up. Thanks for pointing it out!

As soon as I'm at a computer (mobile now) I'll merge this PR and fix the other repo's as well.

PS: Could you add `/composer.lock` to `.gitignore`?

**Comment by jaymecd** [comment]
@jaspernbrouwer done

**Pull request merged**
